#!/bin/sh
# Usage: ag psgrep PATTERN
# Summary: Find running processes using grep
# Help: This is a tiny wrapper to search for a regex PATTERN
# in the output of `ps aux`, excluding the grep process itself.
#
# EXAMPLES
#
# Show all Ruby processes:
#
#     ag psgrep 'ruby'
#

ps aux | awk '/'"$@"'/ && !/ag-psgrep/ { $1 = ""; for(i=3; i <= 10; i++) { $i = "" }; gsub(/^ +|  +/, " ", $0); print $0 }'
